### ISSUE TITLE
check_if_follower()

### ISSUE THREAD

**Issue by xgerhard** [ZERG3R/PythonBot#5]
Hiya! I would appreciate if you used a different source for checking if a user follows a channel. I don't mind, providing this data if a user requests this, by, for example a command, however, not a fan of thousand(s) requests by looping the viewer list. I try to respect the Twitch API soft limit, 1 request a second.

https://github.com/ZERG3R/PythonBot/blob/a367557054dc47f217a29879382e1167dd32c500/bot.py#L513

**Comment by ZERG3R** [comment]
Resolved, I've changed how the data is grabbed so it can not be pinged after the first time per user once the value has been updated in the database. Sorry about that!

**Comment by xgerhard** [comment]
Thanks!
